### ISSUE TITLE
Add open source license

### ISSUE THREAD

**Issue by jcbpl** [cityofaustin/pages#3]
Pending collaboration with Legal.

**Comment by mattlangan** [comment]
@jcbpl Do you want this at the bottom of `README.md` or in its own `LICENSE.md`?

**Comment by mattlangan** [comment]
For future reference, here is the official response from the city's legal department (provided by Sabine Romero) via email on September 23, 2016.

> ... we can proceed with the use of open source licensing.  The original code is a city resource, and to make it open source on Github is to make a service available to the general public (much like a library book), which I am comfortable with from a legal standpoint.

**Comment by jcbpl** [comment]
Oh cool, I didn't know we got approval. LICENSE.md, I think.

**Comment by mattlangan** [comment]
I added an [MIT license](https://github.com/cityofaustin/pages/blob/mit-license/LICENSE.md) and a [CC0 license](https://github.com/cityofaustin/pages/blob/license/LICENSE.md) in separate feature branches for Sabine to review. Once we lock down one I'll submit a PR and delete the other.

/cc @escribbles @benguhin @jcbpl @SabineRomero

**Comment by mattlangan** [comment]
@SabineRomero Please review the two licenses linked above (MIT + CC0) and let us know which we should use.

**Comment by SRomero-ATX** [comment]
Between the two, I would go with CC0, because it leaves the most flexibility to still acknowledge other related legal considerations.

Do note that my comment here is not legal advice (as of October 1, I'm in the Innovation Office, so as of that date my posts are no longer legal advice).
