### ISSUE TITLE
Mobile nav

### ISSUE THREAD

**Issue by jcbpl** [cityofaustin/pages#8]
We could either push the side navigation to the bottom of the page in small viewports (this is what pages.18f.gov does), or if we want, figure out how to make it work with USWDS's mobile overlay menu, which at the moment only seems to be automatic with the horizontal navbar, not the sidenav.

**Comment by mattlangan** [comment]
My CPA solution won't work here as it's really only designed to accommodate up to 5 items. Will look closer at 18F and coordinate with Alex.

**Comment by mattlangan** [comment]
@jcbpl seems like an opportunity to extend USWDS to support hamburger responsiveness on sidenav and contribute back with a PR. I'll try to take a look at this in between ACC work. Might also be worth pinging the 18F folks to see if that's already in development (I'll also look at their Issues to see if it's there).
